<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.10 D:\Node\turtles\static\models\cards.glb --root /models/ --types --printwidth 120 --precision 2 --transform --resolution 1024
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Border: THREE.Mesh
      Rune: THREE.Mesh
      Background: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/cards-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Border.geometry}
      material={gltf.nodes.Border.material}
    />
    <T.Mesh
      geometry={gltf.nodes.Rune.geometry}
      material={gltf.nodes.Rune.material}
    />
    <T.Mesh
      geometry={gltf.nodes.Background.geometry}
      material={gltf.nodes.Background.material}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
